name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Build + deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Setup fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Fly deploy
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
          flyctl deploy